name: 'Delete Artifacts'
description: 'Delete Artifacts'
inputs:
  github_token:
    description: Github token
    required: true
  owner:
    description: Owner
    required: true
  repo:
    description: Respository
    required: true
  name:
    description: Artifact name
    required: true
runs:
  using: 'node16'
  main: 'lib/index.js'